allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.3'
  - '@biomejs/cli-darwin-arm64@2.5.3'
  - '@biomejs/cli-darwin-x64@2.5.3'
  - '@biomejs/cli-linux-arm64-musl@2.5.3'
  - '@biomejs/cli-linux-arm64@2.5.3'
  - '@biomejs/cli-linux-x64-musl@2.5.3'
  - '@biomejs/cli-linux-x64@2.5.3'
  - '@biomejs/cli-win32-arm64@2.5.3'
  - '@biomejs/cli-win32-x64@2.5.3'
  - '@fastify/helmet@13.1.0'
  - '@fastify/static@9.3.0'
  - '@types/node@24.13.3'
