/** 错误码枚举 — 前端与后端共享 */
export const ErrorCode = {
  // 导入
  IMPORT_INVALID_JSON: 'IMPORT_INVALID_JSON',
  IMPORT_SCHEMA_ERROR: 'IMPORT_SCHEMA_ERROR',
  IMPORT_DUPLICATE: 'IMPORT_DUPLICATE',

  // chalaoshi
  CHALAOSHI_NETWORK: 'CHALAOSHI_NETWORK',
  CHALAOSHI_PARSE: 'CHALAOSHI_PARSE',
  CHALAOSHI_NOT_FOUND: 'CHALAOSHI_NOT_FOUND',
  CHALAOSHI_DEGRADED_SEED: 'CHALAOSHI_DEGRADED_SEED',

  // LLM
  LLM_NO_KEY: 'LLM_NO_KEY',
  LLM_NETWORK: 'LLM_NETWORK',
  LLM_TIMEOUT: 'LLM_TIMEOUT',
  LLM_SSRF_BLOCKED: 'LLM_SSRF_BLOCKED',
  LLM_SCHEMA_MISMATCH: 'LLM_SCHEMA_MISMATCH',
  LLM_CONTENT_FILTER: 'LLM_CONTENT_FILTER',

  // 求解
  SOLVER_NO_SOLUTION: 'SOLVER_NO_SOLUTION',
  SOLVER_TIMEOUT: 'SOLVER_TIMEOUT',

  // 校验
  VALIDATION_SCHEMA: 'VALIDATION_SCHEMA',
  VALIDATION_HARD_CONSTRAINT: 'VALIDATION_HARD_CONSTRAINT',
  VALIDATION_LOCK_VIOLATION: 'VALIDATION_LOCK_VIOLATION',

  // 通用
  NETWORK: 'NETWORK',
  UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
