/**
 * 稳定错误码（Task 0 草案）。
 *
 * 规则：
 * - 错误码是跨模块 API 契约的一部分，重命名/删除 = 契约变更，须负责人批准；
 * - 每个错误码只表达一种失败原因；UI 文案由 client 层映射，不在此处写文案；
 * - domain 冲突类错误码同时是求解器"无解 + 冲突来源"输出的载体（D17）。
 */
export const ErrorCodes = {
  // —— 通用 ——
  COMMON_NOT_IMPLEMENTED: "COMMON_NOT_IMPLEMENTED",
  COMMON_INTERNAL: "COMMON_INTERNAL",
  COMMON_VALIDATION_FAILED: "COMMON_VALIDATION_FAILED",

  // —— 导入（组员 A；docs/08 §5.1）——
  IMPORT_INVALID_JSON: "IMPORT_INVALID_JSON",
  IMPORT_SCHEMA_MISMATCH: "IMPORT_SCHEMA_MISMATCH",
  IMPORT_UNKNOWN_SECTION_REF: "IMPORT_UNKNOWN_SECTION_REF",
  IMPORT_DUPLICATE_SECTION: "IMPORT_DUPLICATE_SECTION",
  IMPORT_PRIVACY_SUSPECT: "IMPORT_PRIVACY_SUSPECT",

  // —— chalaoshi（组员 B；抓取失败是常态场景，见 docs/03 §3）——
  CHALAOSHI_UPSTREAM_UNAVAILABLE: "CHALAOSHI_UPSTREAM_UNAVAILABLE",
  CHALAOSHI_RATE_LIMITED: "CHALAOSHI_RATE_LIMITED",
  CHALAOSHI_TIMEOUT: "CHALAOSHI_TIMEOUT",
  CHALAOSHI_PARSE_FAILED: "CHALAOSHI_PARSE_FAILED",

  // —— selection-model（组员 C；性质测试锚点，docs/05 §3.1）——
  MODEL_EXAM_CONFLICT: "MODEL_EXAM_CONFLICT",
  MODEL_CREDIT_LIMIT_EXCEEDED: "MODEL_CREDIT_LIMIT_EXCEEDED",
  MODEL_CREDIT_LIMIT_MISSING: "MODEL_CREDIT_LIMIT_MISSING",
  MODEL_MISSING_EXAM_TIME: "MODEL_MISSING_EXAM_TIME",
  MODEL_MISSING_CREDIT: "MODEL_MISSING_CREDIT",
  MODEL_VOLUNTEER_LIMIT_COURSE: "MODEL_VOLUNTEER_LIMIT_COURSE",
  MODEL_VOLUNTEER_LIMIT_TIMESLOT: "MODEL_VOLUNTEER_LIMIT_TIMESLOT",
  MODEL_SECTION_NOT_IN_POOL: "MODEL_SECTION_NOT_IN_POOL",
  MODEL_LOCK_VIOLATION: "MODEL_LOCK_VIOLATION",
  MODEL_COURSE_GROUP_PRIORITY: "MODEL_COURSE_GROUP_PRIORITY",
  MODEL_NO_FEASIBLE_PLAN: "MODEL_NO_FEASIBLE_PLAN",

  // —— LLM 网关（组员 D；D40 SSRF / D25 Schema）——
  LLM_KEY_MISSING: "LLM_KEY_MISSING",
  LLM_ENDPOINT_NOT_HTTPS: "LLM_ENDPOINT_NOT_HTTPS",
  LLM_ENDPOINT_BLOCKED_SSRF: "LLM_ENDPOINT_BLOCKED_SSRF",
  LLM_CAPABILITY_INSUFFICIENT: "LLM_CAPABILITY_INSUFFICIENT",
  LLM_UPSTREAM_ERROR: "LLM_UPSTREAM_ERROR",
  LLM_TIMEOUT: "LLM_TIMEOUT",
  LLM_RESPONSE_TOO_LARGE: "LLM_RESPONSE_TOO_LARGE",
  LLM_SCHEMA_INVALID: "LLM_SCHEMA_INVALID",
  LLM_ID_OUT_OF_INPUT: "LLM_ID_OUT_OF_INPUT",

  // —— planner / 生成过程（D27）——
  PLAN_GENERATION_CANCELLED: "PLAN_GENERATION_CANCELLED",
  PLAN_STALE_GENERATION: "PLAN_STALE_GENERATION",
  PLAN_FINAL_VALIDATION_FAILED: "PLAN_FINAL_VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/** API 统一错误响应体 */
export interface ApiError {
  errorCode: ErrorCode;
  /** 面向开发者的说明；不得包含隐私字段（D42） */
  message: string;
  /** 可选的结构化细节（如导入错误定位、冲突来源） */
  details?: unknown;
}
